### ISSUE TITLE
__[Tiny Reactors 1.12.2-1.0.1-SNAPSHOT] [BUG] Recipes not working in JEI; Tiny Manual missing__

### ISSUE THREAD

**Issue by Knito58** [ArclightTW/Tiny-Reactors#3]
__Mod Version:__  
Tiny Reactors 1.12.2-1.0.1-SNAPSHOT

__Java Version:__  
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)

__Issue Overview:__   
The recipes of the mod's blocks and items are dead.

__Steps to Recreate:__  
Install JEI, open player GUI, type "@tiny" and click on a block or an item. Nothing happens. In the list of the mod's items the "Tiny Manual" is missing. Cannot craft a single thing as the wiki is text only.

__Crash Log:__  
No.

__Noob Warning__
I'm new to this mod and was all excited about energy from vanilla ores. I try to minimize the count of mods which try to introduce new ores.

**Comment by ArclightTW** [comment]
Fixed in 1.0.2-SNAPSHOT

**Comment by Knito58** [comment]
Thanks. 1.0.2 SNAPSHOT has now working JEI recipes. But the "Tiny Manual" is still missing. Is that manual to be created by a non-recipe action?

**Comment by ArclightTW** [comment]
The "Tiny Manual" has been removed at this time; please use the Wiki if you need assistance. Recipes have now been added there for people not using JEI.

**Comment by Knito58** [comment]
Thanks for the information. JEI seems to run now but I need further wisdom. Will try the WIKI.

**Comment by ArclightTW** [comment]
Feel free to contact me on Twitter if you need further assistance.  Let me know if anything is missing from the Wiki so that I can keep it up to date and as helpful as possible.
